services:
  # paperless-ngx main service
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-ngx
    restart: unless-stopped
    env_file:
      - ./paperless/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./paperless/export:/usr/src/paperless/export
      - ./paperless/consume:/usr/src/paperless/consume

  # postgres database for paperless-ngx
  postgres:
    image: docker.io/library/postgres:18-alpine
    restart: unless-stopped
    container_name: postgres
    env_file:
      - ./postgres/.env
    volumes:
      - pgdata:/var/lib/postgresql

  # redis database for paperless-ngx
  redis:
    image: docker.io/library/redis:8-alpine
    container_name: redis
    restart: unless-stopped
    env_file:
      - ./redis/.env
    volumes:
      - redisdata:/data

  # open-webui service for LLM interaction
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    restart: unless-stopped
    env_file:
      - ./open-webui/.env
    depends_on:
      - ollama
    ports:
      - "3001:8080"
    volumes:
      - open-webuidata:/app/backend/data

  # ollama service for local LLMs
  ollama:
    image: docker.io/ollama/ollama:rocm
    container_name: ollama
    env_file:
      - ./ollama/.env
    volumes:
      - ollamadata/:/root/.ollama
      - ./ollama/models:/ollama-models
    devices:
      - /dev/kfd
      - /dev/dri
    restart: unless-stopped

  # paperless-ai service
  paperless-ai:
    image: docker.io/clusterzx/paperless-ai:latest
    container_name: paperless-ai
    restart: unless-stopped
    depends_on:
      - ollama
      - paperless
    ports:
      - "3000:3000"
    env_file:
      - ./paperless-ai/.env
    volumes:
      - paperless-aidata:/app/data

  # paperless-gpt service
  paperless-gpt:
    image: docker.io/icereed/paperless-gpt:latest
    container_name: paperless-gpt
    restart: unless-stopped
    depends_on:
      - ollama
      - paperless
    ports:
      - "3002:8080"
    env_file:
      - ./paperless-gpt/.env
    volumes:
      - paperless-gpt-prompts:/app/prompts # Mount the prompts directory

  # optional but helpful log viewer
  dozzle:
    image: docker.io/amir20/dozzle:latest
    restart: unless-stopped
    container_name: dozzle
    env_file:
      - ./dozzle/.env
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:ro
      - dozzledata:/data
    ports:
      - "8080:8080"

volumes:
  data:
  media:
  pgdata:
  redisdata:
  open-webuidata:
  ollamadata:
  paperless-aidata:
  paperless-gpt-prompts:
  dozzledata:
